import { useEffect, useState } from "react";

const GeminiApi = ({ flowerList }) => {
  const [generatedImage, setGeneratedImage] = useState("");
  const [error, setError] = useState("");

  useEffect(() => {
    // flowerListが空の場合は処理しない
    if (!flowerList || flowerList.length === 0) return;

    setGeneratedImage("");

    const fetchImage = async () => {
      setError("");

      try {
        // Netlify Functionを呼び出す
        const response = await fetch("/.netlify/functions/generate-bouquet", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            flowerList: flowerList.map((flower) => ({
              filename: flower.filename,
              image: flower.image,
            })),
          }),
        });

        if (!response.ok) {
          throw new Error(`HTTPエラー: ${response.status}`);
        }

        const data = await response.json();

        // Vertex AIからの画像データを処理
        if (data.imageData) {
          setGeneratedImage(`data:image/png;base64,${data.imageData}`);
        } else if (data.error) {
          setError(data.error);
        } else {
          setError("画像の生成に失敗しました");
        }
      } catch (error) {
        setError("エラーが発生しました: " + error.message);
        console.error("Fetch error:", error);
      }
    };

    fetchImage();
  }, [flowerList]);

  return (
    <div>
      <div style={{ maxWidth: "250px" }}>
        {error && (
          <div
            style={{
              color: "red",
              marginBottom: "20px",
              padding: "10px",
              backgroundColor: "#ffe6e6",
              border: "1px solid #ff9999",
              borderRadius: "4px",
            }}
          >
            {error}
          </div>
        )}
        {generatedImage ? (
          <div style={{ textAlign: "center" }}>
            <img
              src={generatedImage}
              alt="Generated by AI"
              style={{
                maxWidth: "100%",
                height: "100%",
                border: "1px solid #ddd",
                borderRadius: "8px",
                boxShadow: "0 4px 8px rgba(0,0,0,0.1)",
              }}
            />
          </div>
        ) : (
          <p>花束作成中...</p>
        )}
      </div>
    </div>
  );
};

export default GeminiApi;
